include include.mk

##############################################################################
# Dependencies
##############################################################################

all: master.lua

#master.lua: master.tpl.lua $(HEADERS)
master.lua: master.tpl.lua

clean:
	$(RM) *.html *~

include rules.mk

